### ISSUE TITLE
How do I interpret the output values?

### ISSUE THREAD

**Issue by raultomescu** [dreamdom/JsSpeechRecognizer#2]
Hi.

Awesome project! One question though, how do I know it knows what I'm saying?
What does the double value represent?

**Comment by dreamdom** [comment]
Glad to hear you like the project! The double value represents a calculated confidence value, with 1 meaning that it matches exactly an entry that you have trained before. I will update the documentation to explain this better.

**Comment by raultomescu** [comment]
That's great. Thanks!
