### ISSUE TITLE
SimpleHTTPServer (Python 2) and http.server (Python 3)

### ISSUE THREAD

**Issue by jtuskan** [dreamdom/JsSpeechRecognizer#3]
README.md minor update to include running SimpleHTTPServer on Python 3

Python 2

``` shell
python -m SimpleHTTPServer 8000
```

Python 3

``` shell
python -m http.server 8000
```

**Comment by DmitryOlkhovoi** [comment]
You know, you can use browser-sync or webpack dev server :)

**Comment by dreamdom** [comment]
Thanks for the suggestions. I have updated the readme file.
